name = "test-backend"
main = "index.js"
compatibility_date = "2024-05-01"

[vars]
SUPABASE_URL = "https://uicyksyhbzywahcltznv.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpY3lrc3loYnp5d2FoY2x0em52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNjg3MzAsImV4cCI6MjA2ODc0NDczMH0.3AXGKaqCh61PDryCZfl8lB6JobgKrQt3J4FKTZ0RnHE" 